[workspace]
authors = ["Giuseppe Di Fatta", "Andrea Rosani", "Thomas Borsani", "Raziyeh Tabatabaei", "Muhammad Ali Bhatti Hafiz"]
channels = ["knime", "conda-forge"]
name = "knimevizlab"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
knime-extension = ">=5.8.0,<6"
knime-python-base = ">=5.5.0,<6"
pytorch = ">=2.5.1,<3"
torchvision = ">=0.20.1,<0.21"
numpy = ">=1.26.4,<2"
pillow = ">=11.2.1,<12"
pandas = ">=2.0.3,<3"

[pypi-dependencies]
opencv-python = "==4.10.0.84"
ultralytics = "==8.3.91"
segment-anything = "==1.0"


[feature.build.dependencies]
python = "3.11.*"
knime-extension-bundling = "5.5.*"


[feature.build.tasks]
build = { args = [{ "arg" = "dest", "default" = "./local-update-site" }], cmd = "python ./.pixi/envs/build/bin/build_python_extension.py . {{ dest }} --disable-strict-enforcement"}

[environments]
build = {features = ["build"], no-default-feature = true}